esphome:
  name: caliper

esp32:
  board: esp32dev
  framework:
    type: arduino ##does not work with esp-idf

api:
ota:
  port: 3232
wifi:
  ssid: <wifi_ssid>
  password: <wifi_password>
logger:

captive_portal:

external_components:
  - source:
      type: local
      path: components

sensor:
  - platform: caliper
    name: Caliper
    id: caliper_reading
